### ISSUE TITLE
🛠️ [Feature]: Git secret, Git Actions로 API_KEY 등록 

### ISSUE THREAD

**Issue by haron-lee** [haron-lee/we-wear-weather#37]
## Description
Git secret, Git Actions로 API_KEY 등록 

## To-do
- [ ] Git secret, Git Actions로 API_KEY 등록 

### Netlify 배포시

1. Netlify에서 설정해주기 
이미 설정해준 상태라면 Site settings > Build & deploy > Environment > Environment variables
![image](https://github.com/haron-lee/we-wear-weather/assets/88657261/62200abc-9be6-45b1-84b2-8f9ecfdb8757)

2. Netlify에서 자동 배포를 막은 후 Github Action, Github secret 사용하기
- Github secret에서 환경변수 API Key 등록
- .github/workflow/netlify.yml 폴더 및 파일 생성

```yml
# workflow 이름
name: Build and Deploy to Netlify

on:
  # master브랜치로 push하면 workflow 실행
  push:
    branches: ['main']

jobs:
  # 현재 build라고 부르는 하나의 job이 존재한다.
  build:
    # runs-on은 job이 어떤 OS에서 실행될지 지정한다.
    runs-on: ubuntu-latest
    
    # steps는 작업들을 순차적으로 실행한다.
    steps:
      # $GITHUB_WORKSPACE에서 저장소를 체크아웃하여, 현재 job이 your 저장소에 접근할 수 있다.  
      - uses: actions/checkout@v2

      # package-lock.json && package.json file 동기화
      - name: Install
        run: rm -f package-lock.json && npm install

      # 빌드
      - name: Build
        run: npm run build

      # deploy
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2

        with:
          #publish할 디렉터리 경로
          publish-dir: './build'     
          #publish할 브랜치 
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
        #깃허브 해당 저장소 -> Settings -> Secrets -> Action에서 따로 설정이 필요하다.
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```

[2번 참고자료](https://geunu97.tistory.com/82)
